kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-1-34
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        feature-gates: "ContainerRestartRules=true"
    controllerManager:
      extraArgs:
        feature-gates: "ContainerRestartRules=true"
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: "ContainerRestartRules=true"
